version: "3.8"
services:
  node-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      #ports=HOST:CONTAINER
      - "3000:3000"
    restart: unless-stopped
  #SEC api handler
  sec-handler:
    build:
      context: ./SEC
      dockerfile: Dockerfile
    ports:
      #ports=HOST:CONTAINER
      - "3003:3003"
    restart: unless-stopped

  #frontend
  vite-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      #ports=HOST:CONTAINER
      - "3001:5173"
    restart: unless-stopped

  java-backend:
    container_name: java-gallega-backend
    restart: always
    build: ./docker
    working_dir: /app
    command: 'mvn clean install spring-boot:run'
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    ports:
      # external:internal
      - "8080:8080"

